#如果使用https,并且使用的是SpringBoot内嵌的tomcat,需要获取客户端正确的ip地址需要以下配置
server:
  tomcat:
    uri-encoding: UTF-8    
    remote-ip-header: x-forwarded-for
  use-forward-headers: true
  
#在SpringBoot 1.5.x版中通过management.security.enabled=false来暴露所有端点，这种方式在2.0之后的版本无效
#去官网查看了2.0之后版本暴露站点的方式,存在两种方式,电无忧选择直接开启并暴露所有站点
management:
  endpoints:
    web:
      exposure:
        include: '*'
