#~作用:如果使用https,并且使用的是SpringBoot内嵌的tomcat,需要获取客户端正确的ip地址需要以下配置
server:
  tomcat:
    uri-encoding: UTF-8    
    remote-ip-header: x-forwarded-for
  use-forward-headers: true

#在SpringBoot 1.5.x版中通过management.security.enabled=false来暴露所有端点，这种方式在2.0之后的版本无效
#去官网查看了2.0之后版本暴露站点的方式,存在两种方式,电无忧选择直接开启并暴露所有站点
#~作用:除开health接口还依赖endpoints.health.sensitive的配置外，其他接口都不需要输入用户名和密码了
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  aop:
    #~该属性值默认为false,表示使用JDK动态代理织入增强;当值为true时,表示使用CGLib动态代理织入增强;
    proxy-target-class: true
    #~springboot此配置是默认开启的,但是配置之后，相当于在程序启动主类中增加了@EnableAspectJAutoProxy注解
    auto: true
  #rabbitmq连接信息
  rabbitmq:
    host: 118.178.141.107
    port: 5672
    username: rabbitadmin
    password: 123456
    #~确认消息发送成功，通过实现ConfirmCallBack接口，消息发送到交换器Exchange后触发回调
    #publisher-confirms: true
    #~这里不需要加/，rabbitMQ 默认就有个/，加了会有2个;springboot 会直接把这个值赋值给虚拟主机变量
    #virtualHost: /
  #redis连接信息
  redis:
    host: 121.40.33.126
    password: dwy121
    port: 6379
    timeout: 0
    #max-active: -1
    #max-wait: -1
    #max-idle: 8
    #min-idle: 0
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #~配置监控统计拦截的filters，去掉后监控界面sql无法统计，stat是统计，wall是SQL防火墙，防SQL注入的，还有一个参数是log4j,是用来输出统计数据的工具类，不配置
    filters: stat,wall
    druid:
      #~初始化大小，最小，最大，应用所有的数据源中
      initial-size: 50
      min-idle: 50
      max-active: 100
      max-wait: 3000
      #~即在获取Connection对象时检测其可用性),不过这样会影响性能,但是这个配置是最有效的
      test-on-borrow: true
      #~配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #~配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #配置Druid的基础监控功能
      web-stat-filter:
        #设置不统计哪些URL
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow:
        #设置监控页面的登录名和密码
        login-username: eraworks
        login-password: druid
  #邮件配置
  mail:
    #~设置邮箱主机
    host: smtp.163.com
    #~设置用户名和密码
    username: eraworks_cloud@163.com
    password: 1qaz@WSX
    port: 465
    protocol: smtp
    test-connection: false
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          #当SMTP需要SSL验证时，需要设定，如果不设定，会出现异常
          starttls:
            enable: true
            required: true
